name: hufc_mobile
description: Offline-first mobile app for Moj Hufiec.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  flutter_local_notifications: ^17.2.4
  flutter_background_service: ^5.1.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/brand/moj-hufiec-logo.png
    - assets/brand/moj-hufiec-icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/brand/moj-hufiec-icon.png
  adaptive_icon_background: "#0B1F14"
  adaptive_icon_foreground: assets/brand/moj-hufiec-icon.png
